name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  id-token: write

jobs:
  build-cad-4:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install .NET Framework 4.7 Developer Pack
      run: |
        choco install netfx-4.7-devpack -y --no-progress
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
      
    - name: Restore Packages
      run: nuget restore BcToolsC.sln

    # Build .NET 4.7 project (ZWCAD)
    - name: Build .NET 4.7 (ZCAD.25)
      run: msbuild BuildsTargets/BcToolsZC25/BcToolsZC25.csproj /t:Restore,Build /p:Configuration=Release /p:DefineConstants=ZWCAD /p:AllowUnsafeBlocks=true
    - name: Build .NET 4.7 (ZCAD.26)
      run: msbuild BuildsTargets/BcToolsZC26/BcToolsZC26.csproj /t:Restore,Build /p:Configuration=Release /p:DefineConstants=ZWCAD /p:AllowUnsafeBlocks=true

    # Build .NET 8.0 project
    - name: Build .NET 8.0 (ACAD.25)
      run: dotnet build BuildsTargets/BcToolsAC25/BcToolsAC25.csproj -c Release /p:AllowUnsafeBlocks=true
    - name: Build .NET 8.0 (ACAD.26)
      run: dotnet build BuildsTargets/BcToolsAC26/BcToolsAC26.csproj -c Release /p:AllowUnsafeBlocks=true
