name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  id-token: write

jobs:
  build-cad-4:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install .NET Framework 4.5 Developer Pack
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri 'https://www.nuget.org/api/v2/package/Microsoft.NETFramework.ReferenceAssemblies.net45/1.0.3' -OutFile "${env:temp}\netfx-4.5-devpack.zip"
        Expand-Archive -Force -LiteralPath "${env:temp}\netfx-4.5-devpack.zip" -DestinationPath "${env:temp}\netfx-4.5-devpack"
        [IO.Directory]::Delete('C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5', $True)
        Move-Item -Force -LiteralPath "${env:temp}\netfx-4.5-devpack\build\.NETFramework\v4.5" -Destination 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'

    - name: Install .NET Framework 4.7 Developer Pack
      run: |
        choco install netfx-4.7-devpack -y --no-progress
    
    - name: Install .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore Packages
      run: nuget restore BcToolsC.sln

    # Build .NET 4.5 project
    - name: Build .NET 4.5 (ACAD.17)
      run: msbuild BuildsTargets/BcToolsAC17/BcToolsAC17.csproj /t:Build /p:Configuration=Release /p:DefineConstants=NET45

    # Build .NET 4.7 project
    - name: Build .NET 4.7 (ZCAD.25)
      run: msbuild BuildsTargets/BcToolsZC25/BcToolsZC25.csproj /t:Build /p:Configuration=Release /p:DefineConstants=ZWCAD /p:AllowUnsafeBlocks=true
    - name: Build .NET 4.7 (ZCAD.26)
      run: msbuild BuildsTargets/BcToolsZC26/BcToolsZC26.csproj /t:Build /p:Configuration=Release /p:DefineConstants=ZWCAD /p:AllowUnsafeBlocks=true

    # Build .NET 8.0 project
    - name: Build .NET 8.0 (ACAD.25)
      run: dotnet build BuildsTargets/BcToolsAC25/BcToolsAC25.csproj -c Release /p:AllowUnsafeBlocks=true
    - name: Build .NET 8.0 (ACAD.26)
      run: dotnet build BuildsTargets/BcToolsAC26/BcToolsAC26.csproj -c Release /p:AllowUnsafeBlocks=true
